name: Build and test with SwiftWasm

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  swiftwasm_build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: swiftwasm/swiftwasm-action@v5.3
        with:
          shell-action: carton test
